version: "3.9"
services:
  discord-bot:
    container_name: Discord-BirthdayBot
    build: .
    env_file:
      - .env
    volumes:
      - /var/log/BirthdayBot:/app/logs
    restart: unless-stopped
