on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  local-build-job:
    runs-on: self-hosted
    steps:
      - name: Move Files
        run: |
          mkdir -p /tmp/Birthday-Bot
          if [ -f .env ]; then
            mv .env /tmp/Birthday-Bot/
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Restore Files
        run: |
          if [ -f /tmp/Birthday-Bot/.env ]; then
            mv /tmp/Birthday-Bot/.env .
          fi
          rm -rf /tmp/Birthday-Bot
          docker compose down
          docker compose build
          docker compose up -d
