on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  local-build-job:
    runs-on: self-hosted
    steps:
      - name: Move Files
        run: |
          mkdir -p /tmp/Birthday-Bot
          mv .env /tmp/Birthday-Bot/ 2>/dev/null

      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Restore Files
        run: |
          mv /tmp/Birthday-Bot/.* . 2>/dev/null
          rm -rf /tmp/Birthday-Bot
          docker compose down
          docker compose up -d
